# Generated by Django 5.1.6 on 2025-02-12 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('title', models.CharField(max_length=255, unique=True)),
                ('subtitle', models.CharField(max_length=255)),
                ('book_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('authors', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('distribution_expense', models.DecimalField(decimal_places=4, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
        ),
    ]
